version: '3.1'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686
  osb:
    environment:
      - TRACING_PROVIDER=JAEGER
      - JAEGER_HOST=jaeger
      - PUSH_GATEWAY_SERVER=pushgateway:9091
      - METRICS_ENABLED=true
