com.instana.plugin.javatrace:
  instrumentation:
    # Lightweight Bytecode Instrumentation, enabled by default
    enabled: true
    # OpenTracing instrumentation, disabled by default
    opentracing: true