<wsdl:definitions name="DispatcherService" targetNamespace="http://xmlns.oracle.com/ServiceBusApplication/SmartMeterDemo/DispatcherService" xmlns:tns="http://xmlns.oracle.com/ServiceBusApplication/SmartMeterDemo/DispatcherService" xmlns:inp1="http://www.sysco.no/smartmeter/demo" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="DispatcherService">
        <plnk:role name="DispatcherServiceProvider" portType="tns:DispatcherService_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sysco.no/smartmeter/demo" schemaLocation="../xsd/smartmeter.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Operation1_inputMessage">
        <wsdl:part name="request" element="inp1:MeterReadingArray"/>
    </wsdl:message>
    <wsdl:message name="Operation1_outputMessage">
        <wsdl:part name="reply" element="inp1:DispatcherResponse"/>
    </wsdl:message>
    <wsdl:message name="Rest_EmptyMessage"/>
    <wsdl:portType name="DispatcherService_ptt">
        <wsdl:operation name="Operation1">
            <wsdl:input message="tns:Operation1_inputMessage"/>
            <wsdl:output message="tns:Operation1_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DispatcherService_ptt-binding" type="tns:DispatcherService_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Operation1">
            <soap:operation soapAction="Operation1"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>