version: '2'
services:
  osb:
    build: osb
    ports:
      - 8001:8001
    environment:
      - PUSH_GATEWAY_SERVER=pushgateway:9091
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
  prom:
    build: prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000